Author: ~ferorge
Date: 2024-02-19
copyright: 2024, ~ferorge, CC BY-SA 4.0.
Email: ferorge@texto-plano.xyz
KeyWords: servidor, publico, libre, pubnix, auto alojado, soberano
css: ../lynx.css


# Gopher

----------------------------------------------------------------------
###### _Gophernicus_

----------------------------------------------------------------------
Gopher es un protocolo de red y un sistema de archivos distribuido  
surgido en la década de 1990 previo al World Wide Web.  
Gopher permite a los usuarios navegar por una jerarquía de menús y  
archivos de texto, imágenes y otros formatos de archivo, utilizando un  
cliente de Gopher o un navegador web con soporte para Gopher.
Con gopher puedes:
- Compartir y distribuir recursos: Gopher facilita la creación y  
distribución de recursos digitales, como documentos, imágenes y  
videos, en una red descentralizada y abierta. Los usuarios pueden  
crear y publicar sus propios recursos en servidores Gopher, y  
compartirlos con otros usuarios de la red.
- Navegar por una jerarquía de menús: Gopher presenta una interfaz de  
navegación basada en menús, lo que facilita la búsqueda y el acceso a  
los recursos disponibles en la red Gopher. Los usuarios pueden navegar  
por categorías y subcategorías de menús, y seleccionar los elementos  
que les interesen.
- Descargar y ver archivos de texto: Gopher admite la transferencia y  
visualización de archivos de texto planos, como artículos, ensayos y  
libros electrónicos. 

----------------------------------------------------------------------
###### _Licencia_

El contenido de este documento está bajo licencia  
[Creative Commons Attribution - Share Alike 4.0][CC BY-SA 4.0]
[CC BY-SA 4.0]:https://creativecommons.org/licenses/by-sa/4.0/deed.es

![Creative Commons Attribution - Share Alike 4.0](https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-sa.png "CC BY-SA 4.0" width=44px height=15px)

----------------------------------------------------------------------
