Author: ~ferorge
Date: 2024-02-19
copyright: 2024, ~ferorge, CC BY-SA 4.0.
Email: ferorge@texto-plano.xyz
KeyWords: servidor, publico, libre, pubnix, auto alojado, soberano
css: ../lynx.css


# Tor proxy

----------------------------------------------------------------------
###### _Tor_

----------------------------------------------------------------------
Tor (The Onion Router) es una red de routing de anonimato que permite  
a los usuarios navegar por Internet de forma anónima y segura.  
Funciona mediante el uso de nodos de relés, que enrutan el tráfico de  
red a través de una serie de saltos aleatorios, lo que dificulta que  
los observadores externos rastreen la actividad en línea de un  
usuario.
Con Tor puedes:  
- Navegar por Internet de forma anónima: Tor te permite navegar por  
Internet de forma anónima, lo que significa que tu dirección IP y tu  
actividad en línea no se pueden rastrear fácilmente.  
Esto es especialmente útil si quieres proteger tu privacidad en línea  
o acceder a contenido censurado o restringido en tu área geográfica.
- Acceder a la Deep Web: Tor es famoso por su capacidad para acceder  
a la Deep Web, una parte de Internet que no está indexada por los  
motores de búsqueda convencionales. La Deep Web alberga una gran  
cantidad de contenido legítimo y valioso, como foros de discusión,  
wikis y blogs, aunque también se sabe que alberga contenido ilegal  
o cuestionable.
- Protección contra el espionaje y la vigilancia: Tor te ayuda a  
protegerte contra el espionaje y la vigilancia en línea, especialmente  
en redes WiFi públicas inseguras. Al enmascarar tu dirección IP y  
enrutar tu tráfico a través de una red descentralizada, reduces el  
riesgo de ser objeto de ataques de phishing, malware o spyware.
- Evitar la censura en línea: Tor te permite evitar la censura en  
línea impuesta por gobiernos u organizaciones restrictivas.  
Al enmascarar tu dirección IP y enrutar tu tráfico a través de una red  
descentralizada, puedes acceder a sitios web y servicios que  
normalmente estarían prohibidos o censurados en tu país o región.
- Publicar contenido de forma anónima: Tor te permite publicar  
contenido de forma anónima en foros, blogs y redes sociales.  
Esto es especialmente útil si quieres compartir opiniones  
controvertidas o sensibles sin enfrentar represalias o consecuencias  
negativas.

----------------------------------------------------------------------
###### _Licencia_

El contenido de este documento está bajo licencia  
[Creative Commons Attribution - Share Alike 4.0][CC BY-SA 4.0]
[CC BY-SA 4.0]:https://creativecommons.org/licenses/by-sa/4.0/deed.es

![Creative Commons Attribution - Share Alike 4.0](https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-sa.png "CC BY-SA 4.0" width=44px height=15px)

----------------------------------------------------------------------
