Language: es
Author: ~ferorge
Email: ferorge@texto-plano.xyz
Affiliation: https://sobnix.ar
Date: 2025-12-22
copyright: 2025, ~ferorge, CC BY-SA 4.0.
KeyWords: servidor, publico, libre, pubnix, auto alojado, soberano
css: lynx.css
Quotes Language: es
Base Header Level: 1

