Language: es
Quotes Language: es
Base Header Level: 1
css: lynx.css
Author: ~ferorge
Email: ferorge@texto-plano.xyz
Affiliation: https://sobnix.ar
Date: 2026-01-03
copyright: 2026, ~ferorge, CC BY-SA 4.0.
KeyWords: servidor, publico, libre, pubnix, auto alojado, soberano
Title: Titulo | Pubnix soberano

