Author: ~ferorge
Date: 2024-02-14
copyright: 2024, ~ferorge, CC BY-SA 4.0.
Email: ferorge@texto-plano.xyz
KeyWords: servidor, publico, libre, pubnix, auto alojado, soberano
css: ../lynx.css

# Servidor HTTP

----------------------------------------------------------------------
###### _Apache2_

----------------------------------------------------------------------
Apache2 es uno de los servidores web libre y de código abierto más  
populares y versátiles disponibles actualmente.  
Algunas cosas que puedes hacer con Apache2 incluyen:

- Servir sitios web estáticos y dinámicos: Apache2 puede servir  
archivos HTML, CSS, JavaScript, imágenes y otros tipos de contenido  
estático directamente desde este servidor.  
También puede trabajar con diversos lenguajes de scripting del lado  
del servidor. Aqui puedes ejecutar ficheros Python para generar  
contenido dinámico en tiempo real.
    
- Integrar con bases de datos: Apache2 puede trabajar con diversos  
motores de base de datos relacionales y no relacionales.  
En este servidor esta disponible mariaDB para proporcionar  
persistencia a aplicaciones web dinámicas.

- Cada usuarie puede crear y publicar su propio sitio web desde su  
directorio personal para que sea accesible por todo el mundo.  
Visita la [guia][Guia] para aprender como crear tu propio sitio web.  
[Guia]:https://tilde.dynv6.net/guias/sitio_web.html
----------------------------------------------------------------------
###### _Licencia_

El contenido de este documento está bajo licencia  
[Creative Commons Attribution - Share Alike 4.0][CC BY-SA 4.0]
[CC BY-SA 4.0]:https://creativecommons.org/licenses/by-sa/4.0/deed.es

![Creative Commons Attribution - Share Alike 4.0](https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-sa.png "CC BY-SA 4.0" width=44px height=15px)

----------------------------------------------------------------------
