Author: ~ferorge
Date: 2024-02-18
copyright: 2024, ~ferorge, CC BY-SA 4.0.
Email: ferorge@texto-plano.xyz
KeyWords: servidor, publico, libre, pubnix, auto alojado, soberano
css: ../lynx.css


# Finger

----------------------------------------------------------------------
###### _fingerd_

----------------------------------------------------------------------
Finger es un programa de shell de Unix y Linux que muestra información  
sobre los usuarios de este servidor o de uno remoto.  
Puedes obtener información sobre el estado, la ubicación de un  
usuario conectado y toda la información personal suministrada al  
administrador del servidor.  
Además cada usuario con dos ficheros para agregar información pública:  
- ~/.project: suele estar limitado a una línea de longitud.  
Puedes indicar en qué proyecto estás trabajando actualmente.  
Suelen ser proyectos a largo plazo o trabajos continuos.  
- ~/.plan: puedes indicar objetivos a corto plazo o cualquier otra  
cosa que desees comunicar a otros usuaries.
- ~/.nofinger: niegas la existencia del usuario.
- ~/.pgp: esta es tu llave pgp.

----------------------------------------------------------------------
###### _Licencia_

El contenido de este documento está bajo licencia  
[Creative Commons Attribution - Share Alike 4.0][CC BY-SA 4.0]
[CC BY-SA 4.0]:https://creativecommons.org/licenses/by-sa/4.0/deed.es

![Creative Commons Attribution - Share Alike 4.0](https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-sa.png "CC BY-SA 4.0" width=44px height=15px)

----------------------------------------------------------------------
