Author: ~ferorge
Date: 2024-02-15
copyright: 2024, ~ferorge, CC BY-SA 4.0.
Email: ferorge@texto-plano.xyz
KeyWords: servidor, publico, libre, pubnix, auto alojado, soberano
css: ../lynx.css


# Base de datos relacional

----------------------------------------------------------------------
###### _MariaDB_

----------------------------------------------------------------------
MariaDB es una base de datos relacional robusta, flexible, libre y de  
código abierto, diseñada como una alternativa compatible con MySQL.  
Fue creada originalmente por los mismos desarrolladores de MySQL  
después de que Oracle adquiriera Sun Microsystems y anunciara planes  
para cambiar la licencia de MySQL a una menos permisiva.  
Cuenta con una comunidad activa de desarrolladores y usuarios que  
contribuyen constantemente con nuevas características y mejoras.

Cada usuarie de este servidor tiene acceso a su propia base de datos.  
Visita la [guia][Guia] para aprender como acceder y usarla.
[Guia]:https://tilde.dynv6.net/guias/base_datos_relacional.html 
----------------------------------------------------------------------
###### _Licencia_

El contenido de este documento está bajo licencia  
[Creative Commons Attribution - Share Alike 4.0][CC BY-SA 4.0]
[CC BY-SA 4.0]:https://creativecommons.org/licenses/by-sa/4.0/deed.es

![Creative Commons Attribution - Share Alike 4.0](https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-sa.png "CC BY-SA 4.0" width=44px height=15px)

----------------------------------------------------------------------
